import type { User } from './utils';
import { md5 } from './utils';

export const users: User[] = [
  {
    id: 'aBcDeFgH',
    firstName: 'John',
    lastName: 'Doe',
    dateOfBirth: '1987-03-12',
    email: 'john.doe@gmail.com',
    password: 'password123',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'xYzAbCdE',
    firstName: 'Emma',
    lastName: 'Johnson',
    dateOfBirth: '1992-08-19',
    email: 'emma.johnson@gmail.com',
    password: 'letmein456',
    jobWanted: 'UX Designer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'pQrStovW',
    firstName: 'Liam',
    lastName: 'Smith',
    dateOfBirth: '1985-05-02',
    email: 'liam.smith@gmail.com',
    password: 'abc123',
    jobWanted: 'Software Engineer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'mNoyqRsT',
    firstName: 'Sophie',
    lastName: 'Brown',
    dateOfBirth: '1990-11-08',
    email: 'sophie.brown@gmail.com',
    password: 'securepass789',
    jobWanted: 'Data Scientist',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'wXyZaBcD',
    firstName: 'Ethan',
    lastName: 'Wilson',
    dateOfBirth: '2001-02-25',
    email: 'ethan.wilson@gmail.com',
    password: 'qwertyuiop',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'kLmNoPqR',
    firstName: 'Olivia',
    lastName: 'Taylor',
    dateOfBirth: '1998-09-14',
    email: 'olivia.taylor@gmail.com',
    password: 'mypassword123',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'gHiJlLmN',
    firstName: 'Ava',
    lastName: 'Martinez',
    dateOfBirth: '2002-06-30',
    email: 'ava.martinez@gmail.com',
    password: 'password456',
    jobWanted: 'Data Analyst',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'dEfGhIjK',
    firstName: 'Noah',
    lastName: 'Gonzalez',
    dateOfBirth: '1989-07-11',
    email: 'noah.gonzalez@gmail.com',
    password: 'letmein789',
    jobWanted: 'Software Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'bCdEfGhI',
    firstName: 'Mia',
    lastName: 'Rivera',
    dateOfBirth: '2000-04-05',
    email: 'mia.rivera@gmail.com',
    password: 'abc123',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'uVwXyZaB',
    firstName: 'William',
    lastName: 'Adams',
    dateOfBirth: '1993-03-28',
    email: 'william.adams@gmail.com',
    password: 'securepass123',
    jobWanted: 'Data Scientist',
    researchStatus: 'Started Training',
  },
  {
    id: 'tUvWxYzA',
    firstName: 'Grace',
    lastName: 'Scott',
    dateOfBirth: '1984-12-16',
    email: 'grace.scott@gmail.com',
    password: 'password789',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'sTuVwXyZ',
    firstName: 'James',
    lastName: 'Murphy',
    dateOfBirth: '1979-10-02',
    email: 'james.murphy@gmail.com',
    password: 'abc456',
    jobWanted: 'Database Administrator',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'rStUvWxY',
    firstName: 'Charlotte',
    lastName: 'Robinson',
    dateOfBirth: '1996-09-20',
    email: 'charlotte.robinson@gmail.com',
    password: 'password234',
    jobWanted: 'Software Engineer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'qRsTuVwX',
    firstName: 'Daniel',
    lastName: 'Walker',
    dateOfBirth: '1983-11-07',
    email: 'daniel.walker@gmail.com',
    password: 'letmein012',
    jobWanted: 'Product Manager',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'pQrStUvW',
    firstName: 'Isabella',
    lastName: 'Lopez',
    dateOfBirth: '2004-05-12',
    email: 'isabella.lopez@gmail.com',
    password: 'abc567',
    jobWanted: 'UX Designer',
    researchStatus: 'Started Training',
  },
  {
    id: 'oPqRsTuV',
    firstName: 'Michael',
    lastName: 'Perez',
    dateOfBirth: '1991-07-26',
    email: 'michael.perez@gmail.com',
    password: 'securepass234',
    jobWanted: 'Backend Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'nOpQrStU',
    firstName: 'Sofia',
    lastName: 'Harris',
    dateOfBirth: '2002-01-08',
    email: 'sofia.harris@gmail.com',
    password: 'password012',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'mNoPqRsT',
    firstName: 'Matthew',
    lastName: 'Clark',
    dateOfBirth: '1997-04-18',
    email: 'matthew.clark@gmail.com',
    password: 'abc678',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'lMnFpQr',
    firstName: 'Ella',
    lastName: 'Young',
    dateOfBirth: '1994-06-03',
    email: 'ella.young@gmail.com',
    password: 'password345',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'kJlMnOpQ',
    firstName: 'Benjamin',
    lastName: 'Turner',
    dateOfBirth: '1982-09-15',
    email: 'benjamin.turner@gmail.com',
    password: 'letmein123',
    jobWanted: 'Product Manager',
    researchStatus: 'Signed Up',
  },
  {
    id: 'iJkLmNoP',
    firstName: 'Avery',
    lastName: 'Adams',
    dateOfBirth: '2003-12-28',
    email: 'avery.adams@gmail.com',
    password: 'abc789',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'hIjKlMnO',
    firstName: 'Luna',
    lastName: 'King',
    dateOfBirth: '1995-08-22',
    email: 'luna.king@gmail.com',
    password: 'securepass456',
    jobWanted: 'UI Designer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'gHiJkLmN',
    firstName: 'Alexander',
    lastName: 'Miller',
    dateOfBirth: '1986-10-11',
    email: 'alexander.miller@gmail.com',
    password: 'password234',
    jobWanted: 'Backend Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'fGhIjKlM',
    firstName: 'Victoria',
    lastName: 'Baker',
    dateOfBirth: '2005-03-14',
    email: 'victoria.baker@gmail.com',
    password: 'abc890',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Started Training',
  },
  {
    id: 'zYxWvUtS',
    firstName: 'Elias',
    lastName: 'Schmidt',
    dateOfBirth: '1991-09-05',
    email: 'elias.schmidt@gmail.com',
    password: 'letmein890',
    jobWanted: 'Software Engineer',
    researchStatus: 'Started Training',
  },
  {
    id: 'aBcDeFgI',
    firstName: 'Amelie',
    lastName: 'Wagner',
    dateOfBirth: '1999-12-15',
    email: 'amelie.wagner@gmail.com',
    password: 'securepass567',
    jobWanted: 'UX Designer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'jKlMnOpQ',
    firstName: 'Hugo',
    lastName: 'Becker',
    dateOfBirth: '1987-07-28',
    email: 'hugo.becker@gmail.com',
    password: 'abc012',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'bCdEfGhO',
    firstName: 'Fiona',
    lastName: 'Hoffmann',
    dateOfBirth: '1994-04-03',
    email: 'fiona.hoffmann@gmail.com',
    password: 'password789',
    jobWanted: 'Data Scientist',
    researchStatus: 'Searched Training',
  },
  {
    id: 'cDeFgHiP',
    firstName: 'Maximilian',
    lastName: 'Schneider',
    dateOfBirth: '1982-11-19',
    email: 'maximilian.schneider@gmail.com',
    password: 'letmein345',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'dEfGhIjQ',
    firstName: 'Mila',
    lastName: 'Schultz',
    dateOfBirth: '2000-01-22',
    email: 'mila.schultz@gmail.com',
    password: 'securepass678',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Started Training',
  },
  {
    id: 'eFgHiJkR',
    firstName: 'Levi',
    lastName: 'Müller',
    dateOfBirth: '1996-06-14',
    email: 'levi.muller@gmail.com',
    password: 'password234',
    jobWanted: 'Data Analyst',
    researchStatus: 'Signed Up',
  },
  {
    id: 'fGhIjKlS',
    firstName: 'Aria',
    lastName: 'Fischer',
    dateOfBirth: '1989-03-07',
    email: 'aria.fischer@gmail.com',
    password: 'abc567',
    jobWanted: 'Software Developer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'gHiJkLmT',
    firstName: 'Theo',
    lastName: 'Weber',
    dateOfBirth: '1993-08-10',
    email: 'theo.weber@gmail.com',
    password: 'letmein901',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'hIjKlMnU',
    firstName: 'Eva',
    lastName: 'Schulz',
    dateOfBirth: '2001-02-18',
    email: 'eva.schulz@gmail.com',
    password: 'securepass345',
    jobWanted: 'UX Designer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'iJkLmNoV',
    firstName: 'Gabriel',
    lastName: 'Koch',
    dateOfBirth: '1990-12-03',
    email: 'gabriel.koch@gmail.com',
    password: 'password678',
    jobWanted: 'Software Engineer',
    researchStatus: 'Started Training',
  },
  {
    id: 'jKlMnOpW',
    firstName: 'Lina',
    lastName: 'Bauer',
    dateOfBirth: '1984-10-26',
    email: 'lina.bauer@gmail.com',
    password: 'abc234',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'kLmNoPqX',
    firstName: 'Lucas',
    lastName: 'Schmitt',
    dateOfBirth: '2003-05-09',
    email: 'lucas.schmitt@gmail.com',
    password: 'letmein567',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'lMnOpQrY',
    firstName: 'Clara',
    lastName: 'Richter',
    dateOfBirth: '1985-09-17',
    email: 'clara.richter@gmail.com',
    password: 'securepass890',
    jobWanted: 'Data Scientist',
    researchStatus: 'Searched Training',
  },
  {
    id: 'mNoPqRsZ',
    firstName: 'Luca',
    lastName: 'Krause',
    dateOfBirth: '1997-04-11',
    email: 'luca.krause@gmail.com',
    password: 'password123',
    jobWanted: 'Backend Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'nOpQrStA',
    firstName: 'Emilia',
    lastName: 'Schreiber',
    dateOfBirth: '2004-07-01',
    email: 'emilia.schreiber@gmail.com',
    password: 'abc456',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Started Training',
  },
  {
    id: 'oPqRsTuB',
    firstName: 'Oscar',
    lastName: 'Neumann',
    dateOfBirth: '1992-11-28',
    email: 'oscar.neumann@gmail.com',
    password: 'letmein789',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'pQrStUvC',
    firstName: 'Sophia',
    lastName: 'Wolff',
    dateOfBirth: '1998-01-05',
    email: 'sophia.wolff@gmail.com',
    password: 'securepass012',
    jobWanted: 'UI Designer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'qRsTuVwD',
    firstName: 'David',
    lastName: 'Hartmann',
    dateOfBirth: '1986-12-09',
    email: 'david.hartmann@gmail.com',
    password: 'password345',
    jobWanted: 'Backend Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'rStUvWxE',
    firstName: 'Aurora',
    lastName: 'Kühn',
    dateOfBirth: '1995-03-20',
    email: 'aurora.kuhn@gmail.com',
    password: 'abc567',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'sTuVwXyF',
    firstName: 'Julian',
    lastName: 'Lange',
    dateOfBirth: '2002-06-18',
    email: 'julian.lange@gmail.com',
    password: 'letmein890',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'tUvWxYzG',
    firstName: 'Elena',
    lastName: 'Vogel',
    dateOfBirth: '1983-04-07',
    email: 'elena.vogel@gmail.com',
    password: 'securepass567',
    jobWanted: 'Data Scientist',
    researchStatus: 'Signed Up',
  },
  {
    id: 'uVwXyZaH',
    firstName: 'Liam',
    lastName: 'Hermann',
    dateOfBirth: '2000-09-12',
    email: 'liam.hermann@gmail.com',
    password: 'password123',
    jobWanted: 'Software Engineer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'vWxYzAbI',
    firstName: 'Mila',
    lastName: 'Jäger',
    dateOfBirth: '1991-08-27',
    email: 'mila.jager@gmail.com',
    password: 'abc456',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'wXyZaBcJ',
    firstName: 'Felix',
    lastName: 'Graf',
    dateOfBirth: '1987-10-03',
    email: 'felix.graf@gmail.com',
    password: 'letmein789',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'xYzAbCdK',
    firstName: 'Lina',
    lastName: 'Böhm',
    dateOfBirth: '1996-12-19',
    email: 'lina.bohm@gmail.com',
    password: 'securepass012',
    jobWanted: 'Backend Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'yZaBcDeL',
    firstName: 'Finn',
    lastName: 'Schwartz',
    dateOfBirth: '1985-05-18',
    email: 'finn.schwartz@gmail.com',
    password: 'abc123',
    jobWanted: 'Software Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'zAbCdEfM',
    firstName: 'Ella',
    lastName: 'Zimmermann',
    dateOfBirth: '2003-01-14',
    email: 'ella.zimmermann@gmail.com',
    password: 'password456',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'bCdEfGhN',
    firstName: 'Noah',
    lastName: 'Haas',
    dateOfBirth: '1989-03-22',
    email: 'noah.haas@gmail.com',
    password: 'letmein789',
    jobWanted: 'UI Designer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'cDeFgHiO',
    firstName: 'Emilia',
    lastName: 'Roth',
    dateOfBirth: '1994-07-30',
    email: 'emilia.roth@gmail.com',
    password: 'securepass012',
    jobWanted: 'Data Scientist',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'dEfGhIjP',
    firstName: 'Hannes',
    lastName: 'Werner',
    dateOfBirth: '1982-09-05',
    email: 'hannes.werner@gmail.com',
    password: 'abc567',
    jobWanted: 'Software Engineer',
    researchStatus: 'Started Training',
  },
  {
    id: 'eFgHiJkQ',
    firstName: 'Mila',
    lastName: 'Schneider',
    dateOfBirth: '1998-11-10',
    email: 'mila.schneider@gmail.com',
    password: 'password234',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'fGhIjKlR',
    firstName: 'Ben',
    lastName: 'Beck',
    dateOfBirth: '2002-04-07',
    email: 'ben.beck@gmail.com',
    password: 'abc890',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'gHiJkLmS',
    firstName: 'Mia',
    lastName: 'Müller',
    dateOfBirth: '1984-06-12',
    email: 'mia.muller@gmail.com',
    password: 'securepass123',
    jobWanted: 'Backend Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'hIjKlMnT',
    firstName: 'Liam',
    lastName: 'Fuchs',
    dateOfBirth: '2000-08-19',
    email: 'liam.fuchs@gmail.com',
    password: 'letmein456',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'iJkLmNoU',
    firstName: 'Elena',
    lastName: 'Schmidt',
    dateOfBirth: '1993-02-14',
    email: 'elena.schmidt@gmail.com',
    password: 'abc012',
    jobWanted: 'UI Designer',
    researchStatus: 'Started Training',
  },
  {
    id: 'jKlMnOpV',
    firstName: 'Oscar',
    lastName: 'Herzog',
    dateOfBirth: '1987-09-28',
    email: 'oscar.herzog@gmail.com',
    password: 'password789',
    jobWanted: 'Data Scientist',
    researchStatus: 'Signed Up',
  },
  {
    id: 'kLmNoPqW',
    firstName: 'Emily',
    lastName: 'Lehmann',
    dateOfBirth: '2001-11-22',
    email: 'emily.lehmann@gmail.com',
    password: 'securepass567',
    jobWanted: 'Software Engineer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'lMnOpQrX',
    firstName: 'Finn',
    lastName: 'Schwarz',
    dateOfBirth: '1996-10-17',
    email: 'finn.schwarz@gmail.com',
    password: 'abc234',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'mNoPqRsY',
    firstName: 'Emma',
    lastName: 'Bachmann',
    dateOfBirth: '1992-01-08',
    email: 'emma.bachmann@gmail.com',
    password: 'letmein890',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'nOpQrStZ',
    firstName: 'Elias',
    lastName: 'Graf',
    dateOfBirth: '1989-04-19',
    email: 'elias.graf@gmail.com',
    password: 'securepass345',
    jobWanted: 'Backend Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'oPqRsTuA',
    firstName: 'Mila',
    lastName: 'Kuhn',
    dateOfBirth: '1998-07-11',
    email: 'mila.kuhn@gmail.com',
    password: 'password567',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'pQrStUvB',
    firstName: 'Liam',
    lastName: 'Wolff',
    dateOfBirth: '2002-12-30',
    email: 'liam.wolff@gmail.com',
    password: 'abc123',
    jobWanted: 'UI Designer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'qRsTuVwC',
    firstName: 'Luna',
    lastName: 'Hartmann',
    dateOfBirth: '1985-02-25',
    email: 'luna.hartmann@gmail.com',
    password: 'letmein456',
    jobWanted: 'Data Scientist',
    researchStatus: 'Searched Training',
  },
  {
    id: 'rStUvWxD',
    firstName: 'Max',
    lastName: 'Baumann',
    dateOfBirth: '2000-06-18',
    email: 'max.baumann@gmail.com',
    password: 'securepass789',
    jobWanted: 'Backend Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'sTuVwXyE',
    firstName: 'Eva',
    lastName: 'Kühn',
    dateOfBirth: '1984-09-30',
    email: 'eva.kuhn@gmail.com',
    password: 'password234',
    jobWanted: 'Software Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'tUvWxYzF',
    firstName: 'Noah',
    lastName: 'Jäger',
    dateOfBirth: '1992-01-12',
    email: 'noah.jager@gmail.com',
    password: 'abc567',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'uVwXyZaG',
    firstName: 'Mia',
    lastName: 'Schmidt',
    dateOfBirth: '1987-04-15',
    email: 'mia.schmidt@gmail.com',
    password: 'letmein890',
    jobWanted: 'UX Designer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'vWxYzAbH',
    firstName: 'Elias',
    lastName: 'Wagner',
    dateOfBirth: '1995-06-28',
    email: 'elias.wagner@gmail.com',
    password: 'securepass012',
    jobWanted: 'Software Engineer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'wXyZaBcI',
    firstName: 'Emma',
    lastName: 'Fischer',
    dateOfBirth: '2001-03-18',
    email: 'emma.fischer@gmail.com',
    password: 'password567',
    jobWanted: 'Data Analyst',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'xYzAbCdJ',
    firstName: 'Liam',
    lastName: 'Möller',
    dateOfBirth: '1994-08-12',
    email: 'liam.moller@gmail.com',
    password: 'abc234',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'yZaBcDeK',
    firstName: 'Mila',
    lastName: 'Schneider',
    dateOfBirth: '1988-02-23',
    email: 'mila.schneider@gmail.com',
    password: 'letmein567',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'zAbCdEfL',
    firstName: 'Noah',
    lastName: 'Koch',
    dateOfBirth: '2004-04-15',
    email: 'noah.koch@gmail.com',
    password: 'securepass789',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'bCdEfGhM',
    firstName: 'Mia',
    lastName: 'Becker',
    dateOfBirth: '1990-07-19',
    email: 'mia.becker@gmail.com',
    password: 'password012',
    jobWanted: 'UX Designer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'cDeFgHiN',
    firstName: 'Elias',
    lastName: 'Graf',
    dateOfBirth: '1986-09-23',
    email: 'elias.graf@gmail.com',
    password: 'abc567',
    jobWanted: 'Software Engineer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'dEfGhIjO',
    firstName: 'Emma',
    lastName: 'Herzog',
    dateOfBirth: '1993-11-14',
    email: 'emma.herzog@gmail.com',
    password: 'letmein890',
    jobWanted: 'Data Scientist',
    researchStatus: 'Started Training',
  },
  {
    id: 'eFgHiJkP',
    firstName: 'Liam',
    lastName: 'Schwarz',
    dateOfBirth: '1999-12-16',
    email: 'liam.schwarz@gmail.com',
    password: 'securepass234',
    jobWanted: 'Backend Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'fGhIjKlQ',
    firstName: 'Mia',
    lastName: 'Kühn',
    dateOfBirth: '2003-08-29',
    email: 'mia.kuhn@gmail.com',
    password: 'password567',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'gHiJkLmR',
    firstName: 'Noah',
    lastName: 'Jäger',
    dateOfBirth: '1984-07-18',
    email: 'noah.jager@gmail.com',
    password: 'abc890',
    jobWanted: 'Software Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'hIjKlMnS',
    firstName: 'Emma',
    lastName: 'Schmidt',
    dateOfBirth: '1991-02-22',
    email: 'emma.schmidt@gmail.com',
    password: 'letmein123',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'iJkLmNoT',
    firstName: 'Liam',
    lastName: 'Wagner',
    dateOfBirth: '1996-05-26',
    email: 'liam.wagner@gmail.com',
    password: 'abc456',
    jobWanted: 'UX Designer',
    researchStatus: 'Started Training',
  },
  {
    id: 'jKlMnOpU',
    firstName: 'Mia',
    lastName: 'Fischer',
    dateOfBirth: '2000-09-30',
    email: 'mia.fischer@gmail.com',
    password: 'password789',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'kLmNoPqV',
    firstName: 'Liam',
    lastName: 'Graf',
    dateOfBirth: '1989-01-23',
    email: 'liam.graf@gmail.com',
    password: 'letmein012',
    jobWanted: 'Data Analyst',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'lMnOpQrW',
    firstName: 'Emma',
    lastName: 'Herzog',
    dateOfBirth: '1995-04-17',
    email: 'emma.herzog@gmail.com',
    password: 'abc567',
    jobWanted: 'Software Engineer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'mNoPqRsX',
    firstName: 'Noah',
    lastName: 'Schwarz',
    dateOfBirth: '1987-06-12',
    email: 'noah.schwarz@gmail.com',
    password: 'securepass890',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'nOpQrStY',
    firstName: 'Mia',
    lastName: 'Kühn',
    dateOfBirth: '2001-07-15',
    email: 'mia.kuhn@gmail.com',
    password: 'password123',
    jobWanted: 'UX Designer',
    researchStatus: 'Started Training',
  },
  {
    id: 'oPqRsTuZ',
    firstName: 'Noah',
    lastName: 'Jäger',
    dateOfBirth: '1983-10-29',
    email: 'noah.jager@gmail.com',
    password: 'letmein456',
    jobWanted: 'Data Scientist',
    researchStatus: 'Signed Up',
  },
  {
    id: 'pQrStUvA',
    firstName: 'Mia',
    lastName: 'Fischer',
    dateOfBirth: '1998-12-05',
    email: 'mia.fischer@gmail.com',
    password: 'securepass789',
    jobWanted: 'Software Engineer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'qRsTuVwB',
    firstName: 'Noah',
    lastName: 'Graf',
    dateOfBirth: '1986-03-18',
    email: 'noah.graf@gmail.com',
    password: 'abc012',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'rStUvWxC',
    firstName: 'Emma',
    lastName: 'Schwarz',
    dateOfBirth: '1992-06-30',
    email: 'emma.schwarz@gmail.com',
    password: 'letmein345',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'sTuVwXyD',
    firstName: 'Noah',
    lastName: 'Jäger',
    dateOfBirth: '1996-08-14',
    email: 'noah.jager@gmail.com',
    password: 'abc567',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'tUvWxYzE',
    firstName: 'Mia',
    lastName: 'Fischer',
    dateOfBirth: '2000-11-27',
    email: 'mia.fischer@gmail.com',
    password: 'password789',
    jobWanted: 'Backend Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'uVwXyZaF',
    firstName: 'Noah',
    lastName: 'Graf',
    dateOfBirth: '1984-02-10',
    email: 'noah.graf@gmail.com',
    password: 'letmein012',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'vWxYzAbG',
    firstName: 'Mia',
    lastName: 'Schwarz',
    dateOfBirth: '1998-05-22',
    email: 'mia.schwarz@gmail.com',
    password: 'abc345',
    jobWanted: 'Software Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'wXyZaBcH',
    firstName: 'Noah',
    lastName: 'Jäger',
    dateOfBirth: '1985-09-15',
    email: 'noah.jager@gmail.com',
    password: 'letmein567',
    jobWanted: 'UI Designer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'xYzAbCdI',
    firstName: 'Mia',
    lastName: 'Fischer',
    dateOfBirth: '1999-12-18',
    email: 'mia.fischer@gmail.com',
    password: 'abc789',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'yZaBcDeJ',
    firstName: 'Noah',
    lastName: 'Graf',
    dateOfBirth: '2003-01-20',
    email: 'noah.graf@gmail.com',
    password: 'letmein012',
    jobWanted: 'Data Analyst',
    researchStatus: 'Signed Up',
  },
  {
    id: 'zAbCdEfK',
    firstName: 'Mia',
    lastName: 'Schwarz',
    dateOfBirth: '1987-03-24',
    email: 'mia.schwarz@gmail.com',
    password: 'abc234',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'bCdEfGhL',
    firstName: 'Noah',
    lastName: 'Jäger',
    dateOfBirth: '1992-05-28',
    email: 'noah.jager@gmail.com',
    password: 'letmein456',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'cDeFgHiM',
    firstName: 'Mia',
    lastName: 'Fischer',
    dateOfBirth: '1996-09-30',
    email: 'mia.fischer@gmail.com',
    password: 'abc567',
    jobWanted: 'Software Engineer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'dEfGhIjN',
    firstName: 'Noah',
    lastName: 'Graf',
    dateOfBirth: '2001-12-23',
    email: 'noah.graf@gmail.com',
    password: 'letmein678',
    jobWanted: 'Backend Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'eFgHiJkO',
    firstName: 'Mia',
    lastName: 'Schwarz',
    dateOfBirth: '1988-03-27',
    email: 'mia.schwarz@gmail.com',
    password: 'abc789',
    jobWanted: 'Data Scientist',
    researchStatus: 'Signed Up',
  },
  {
    id: 'fGhIjKlP',
    firstName: 'Noah',
    lastName: 'Jäger',
    dateOfBirth: '1993-06-30',
    email: 'noah.jager@gmail.com',
    password: 'letmein890',
    jobWanted: 'Software Developer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'gHiJkLmQ',
    firstName: 'Mia',
    lastName: 'Fischer',
    dateOfBirth: '1997-09-23',
    email: 'mia.fischer@gmail.com',
    password: 'abc012',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'hIjKlMnR',
    firstName: 'Noah',
    lastName: 'Graf',
    dateOfBirth: '2002-10-26',
    email: 'noah.graf@gmail.com',
    password: 'letmein123',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'iJkLmNoS',
    firstName: 'Mia',
    lastName: 'Schwarz',
    dateOfBirth: '1984-11-29',
    email: 'mia.schwarz@gmail.com',
    password: 'abc234',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'jKlMnOpT',
    firstName: 'Noah',
    lastName: 'Jäger',
    dateOfBirth: '1989-02-18',
    email: 'noah.jager@gmail.com',
    password: 'letmein345',
    jobWanted: 'Data Analyst',
    researchStatus: 'Signed Up',
  },
  {
    id: 'kLmNoPqU',
    firstName: 'Mia',
    lastName: 'Fischer',
    dateOfBirth: '1995-05-31',
    email: 'mia.fischer@gmail.com',
    password: 'abc456',
    jobWanted: 'Software Engineer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'lMnOpQrV',
    firstName: 'Noah',
    lastName: 'Graf',
    dateOfBirth: '2000-06-20',
    email: 'noah.graf@gmail.com',
    password: 'letmein567',
    jobWanted: 'Backend Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'mNoPqRsW',
    firstName: 'Mia',
    lastName: 'Schwarz',
    dateOfBirth: '2004-07-15',
    email: 'mia.schwarz@gmail.com',
    password: 'abc678',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'nOpQrStX',
    firstName: 'Noah',
    lastName: 'Jäger',
    dateOfBirth: '1986-08-29',
    email: 'noah.jager@gmail.com',
    password: 'letmein789',
    jobWanted: 'Data Scientist',
    researchStatus: 'Started Training',
  },
  {
    id: 'oPqRsTuY',
    firstName: 'Mia',
    lastName: 'Fischer',
    dateOfBirth: '1991-09-18',
    email: 'mia.fischer@gmail.com',
    password: 'abc890',
    jobWanted: 'Software Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'pQrStUvZ',
    firstName: 'Noah',
    lastName: 'Graf',
    dateOfBirth: '1996-10-20',
    email: 'noah.graf@gmail.com',
    password: 'letmein012',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'qRsTuVwA',
    firstName: 'Mia',
    lastName: 'Schwarz',
    dateOfBirth: '2001-11-29',
    email: 'mia.schwarz@gmail.com',
    password: 'abc123',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'rStUvWxB',
    firstName: 'Noah',
    lastName: 'Jäger',
    dateOfBirth: '1984-12-20',
    email: 'noah.jager@gmail.com',
    password: 'letmein234',
    jobWanted: 'Backend Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'sTuVwXyC',
    firstName: 'Mia',
    lastName: 'Fischer',
    dateOfBirth: '1989-01-18',
    email: 'mia.fischer@gmail.com',
    password: 'abc345',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Started Training',
  },
  {
    id: 'tUvWxYzD',
    firstName: 'Noah',
    lastName: 'Graf',
    dateOfBirth: '1994-02-21',
    email: 'noah.graf@gmail.com',
    password: 'letmein456',
    jobWanted: 'Software Engineer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'uVwXyZaE',
    firstName: 'Mia',
    lastName: 'Schwarz',
    dateOfBirth: '1999-03-30',
    email: 'mia.schwarz@gmail.com',
    password: 'abc567',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'vWxYzAbF',
    firstName: 'Noah',
    lastName: 'Jäger',
    dateOfBirth: '2003-04-22',
    email: 'noah.jager@gmail.com',
    password: 'letmein678',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'wXyZaBcG',
    firstName: 'Mia',
    lastName: 'Fischer',
    dateOfBirth: '1987-05-25',
    email: 'mia.fischer@gmail.com',
    password: 'abc789',
    jobWanted: 'Data Scientist',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'xYzAbCdH',
    firstName: 'Noah',
    lastName: 'Graf',
    dateOfBirth: '1992-06-27',
    email: 'noah.graf@gmail.com',
    password: 'letmein890',
    jobWanted: 'Backend Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'yZaBcDeI',
    firstName: 'Mia',
    lastName: 'Schwarz',
    dateOfBirth: '1997-07-29',
    email: 'mia.schwarz@gmail.com',
    password: 'abc012',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'zAbCdEfJ',
    firstName: 'Noah',
    lastName: 'Jäger',
    dateOfBirth: '2002-08-22',
    email: 'noah.jager@gmail.com',
    password: 'letmein123',
    jobWanted: 'Software Developer',
    researchStatus: 'Entered Criteria',
  },
];

for (const user of users) {
  user.email = md5(user.email);
  user.password = md5(user.password);
}
