import type { User } from './utils';
import { md5 } from './utils';

export const users: User[] = [
  {
    id: 'gHiJkLmQ',
    firstName: 'Lucas',
    lastName: 'Dupont',
    dateOfBirth: '1995-09-08',
    email: 'lucas.dupont@gmail.com',
    password: 'letmein123',
    jobWanted: 'Software Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'hIjKlMnP',
    firstName: 'Elena',
    lastName: 'García',
    dateOfBirth: '1992-11-15',
    email: 'elena.garcia@gmail.com',
    password: 'password456',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'iJkLmNoQ',
    firstName: 'Francesco',
    lastName: 'Ricci',
    dateOfBirth: '1987-04-20',
    email: 'francesco.ricci@gmail.com',
    password: 'securepass789',
    jobWanted: 'UX Designer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'jKlMnOpR',
    firstName: 'Manuela',
    lastName: 'López',
    dateOfBirth: '1998-06-25',
    email: 'manuela.lopez@gmail.com',
    password: 'letmeinabc',
    jobWanted: 'Data Scientist',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'kLmNpQrS',
    firstName: 'Alexandre',
    lastName: 'Martin',
    dateOfBirth: '1990-12-10',
    email: 'alexandre.martin@gmail.com',
    password: 'password123',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'lMnOpQrT',
    firstName: 'Clara',
    lastName: 'Santos',
    dateOfBirth: '1984-02-18',
    email: 'clara.santos@gmail.com',
    password: 'securepass456',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'mNpQrStU',
    firstName: 'Alessio',
    lastName: 'Rossi',
    dateOfBirth: '1993-07-28',
    email: 'alessio.rossi@gmail.com',
    password: 'abc123',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'nPqRsTuV',
    firstName: 'Gabrielle',
    lastName: 'Lefèvre',
    dateOfBirth: '1996-10-05',
    email: 'gabrielle.lefevre@gmail.com',
    password: 'letmein789',
    jobWanted: 'Backend Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'oPqRsHuV',
    firstName: 'Rafael',
    lastName: 'Gómez',
    dateOfBirth: '1988-03-15',
    email: 'rafael.gomez@gmail.com',
    password: 'abc456',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'pQrStGvW',
    firstName: 'Chiara',
    lastName: 'Conti',
    dateOfBirth: '1991-12-22',
    email: 'chiara.conti@gmail.com',
    password: 'securepass567',
    jobWanted: 'Software Engineer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'qRsTHVwX',
    firstName: 'Hugo',
    lastName: 'López',
    dateOfBirth: '1997-04-07',
    email: 'hugo.lopez@gmail.com',
    password: 'letmein890',
    jobWanted: 'UI Designer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'rStUvXxY',
    firstName: 'Luna',
    lastName: 'Rodríguez',
    dateOfBirth: '2000-08-19',
    email: 'luna.rodriguez@gmail.com',
    password: 'password234',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'sTuVHXyZ',
    firstName: 'Matteo',
    lastName: 'Bianchi',
    dateOfBirth: '1989-02-26',
    email: 'matteo.bianchi@gmail.com',
    password: 'securepass678',
    jobWanted: 'Data Analyst',
    researchStatus: 'Signed Up',
  },
  {
    id: 'tUvWAYzA',
    firstName: 'Emma',
    lastName: 'Martínez',
    dateOfBirth: '1994-06-09',
    email: 'emma.martinez@gmail.com',
    password: 'abc789',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'uVwAyZaB',
    firstName: 'Giovanni',
    lastName: 'Ferrari',
    dateOfBirth: '1999-09-13',
    email: 'giovanni.ferrari@gmail.com',
    password: 'letmein012',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'vWxYzAbC',
    firstName: 'Sophie',
    lastName: 'Lacroix',
    dateOfBirth: '1992-03-17',
    email: 'sophie.lacroix@gmail.com',
    password: 'password890',
    jobWanted: 'Software Engineer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'wXyVaBcD',
    firstName: 'Diego',
    lastName: 'Sánchez',
    dateOfBirth: '1998-05-24',
    email: 'diego.sanchez@gmail.com',
    password: 'securepass012',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'xYzAKCdE',
    firstName: 'Eva',
    lastName: 'Moreau',
    dateOfBirth: '1987-09-29',
    email: 'eva.moreau@gmail.com',
    password: 'letmein345',
    jobWanted: 'Backend Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'yZaBcDeF',
    firstName: 'Antonio',
    lastName: 'Rizzo',
    dateOfBirth: '1995-11-14',
    email: 'antonio.rizzo@gmail.com',
    password: 'abc678',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'zAbCdEfG',
    firstName: 'Isabella',
    lastName: 'Marini',
    dateOfBirth: '1991-02-08',
    email: 'isabella.marini@gmail.com',
    password: 'securepass901',
    jobWanted: 'UI Designer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'aBcDeFgH',
    firstName: 'Alexander',
    lastName: 'Müller',
    dateOfBirth: '1987-03-12',
    email: 'alexander.muller@gmail.com',
    password: 'password123',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'xYzAbCdE',
    firstName: 'Sophia',
    lastName: 'Schneider',
    dateOfBirth: '1992-08-19',
    email: 'sophia.schneider@gmail.com',
    password: 'letmein456',
    jobWanted: 'UX Designer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'pQrStovW',
    firstName: 'David',
    lastName: 'Weber',
    dateOfBirth: '1985-05-02',
    email: 'david.weber@gmail.com',
    password: 'abc123',
    jobWanted: 'Software Engineer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'mNoyqRsT',
    firstName: 'Maria',
    lastName: 'Fischer',
    dateOfBirth: '1990-11-08',
    email: 'maria.fischer@gmail.com',
    password: 'securepass789',
    jobWanted: 'Data Scientist',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'wXyZaBcD',
    firstName: 'Daniel',
    lastName: 'Wagner',
    dateOfBirth: '2001-02-25',
    email: 'daniel.wagner@gmail.com',
    password: 'qwertyuiop',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'kLmNoPqR',
    firstName: 'Emma',
    lastName: 'Schmitt',
    dateOfBirth: '1998-09-14',
    email: 'emma.schmitt@gmail.com',
    password: 'mypassword123',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'gHiJlLmN',
    firstName: 'Leon',
    lastName: 'Becker',
    dateOfBirth: '2002-06-30',
    email: 'leon.becker@gmail.com',
    password: 'password456',
    jobWanted: 'Data Analyst',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'dEfGhIjK',
    firstName: 'Mia',
    lastName: 'Meyer',
    dateOfBirth: '1989-07-11',
    email: 'mia.meyer@gmail.com',
    password: 'letmein789',
    jobWanted: 'Software Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'bCdEfGhI',
    firstName: 'Paul',
    lastName: 'Hoffmann',
    dateOfBirth: '2000-04-05',
    email: 'paul.hoffmann@gmail.com',
    password: 'abc123',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'uVwXyZaB',
    firstName: 'Sofia',
    lastName: 'Schulz',
    dateOfBirth: '1993-03-28',
    email: 'sofia.schulz@gmail.com',
    password: 'securepass123',
    jobWanted: 'Data Scientist',
    researchStatus: 'Started Training',
  },
  {
    id: 'tUvWxYzA',
    firstName: 'Lukas',
    lastName: 'Schäfer',
    dateOfBirth: '1984-12-16',
    email: 'lukas.schafer@gmail.com',
    password: 'password789',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'sTuVwXyZ',
    firstName: 'Anna',
    lastName: 'Lange',
    dateOfBirth: '1979-10-02',
    email: 'anna.lange@gmail.com',
    password: 'abc456',
    jobWanted: 'Database Administrator',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'rStUvWxY',
    firstName: 'Finn',
    lastName: 'Bauer',
    dateOfBirth: '1996-09-20',
    email: 'finn.bauer@gmail.com',
    password: 'password234',
    jobWanted: 'Software Engineer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'qRsTuVwX',
    firstName: 'Amalia',
    lastName: 'Schwarz',
    dateOfBirth: '1983-11-07',
    email: 'amalia.schwarz@gmail.com',
    password: 'letmein012',
    jobWanted: 'Product Manager',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'pQrStUvW',
    firstName: 'Jakob',
    lastName: 'Hartmann',
    dateOfBirth: '2004-05-12',
    email: 'jakob.hartmann@gmail.com',
    password: 'abc567',
    jobWanted: 'UX Designer',
    researchStatus: 'Started Training',
  },
  {
    id: 'oPqRsTuV',
    firstName: 'Lena',
    lastName: 'Neumann',
    dateOfBirth: '1991-07-26',
    email: 'lena.neumann@gmail.com',
    password: 'securepass234',
    jobWanted: 'Backend Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'nOpQrStU',
    firstName: 'Timo',
    lastName: 'Herrmann',
    dateOfBirth: '2002-01-08',
    email: 'timo.herrmann@gmail.com',
    password: 'password012',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'mNoPqRsT',
    firstName: 'Elias',
    lastName: 'Richter',
    dateOfBirth: '1997-04-18',
    email: 'elias.richter@gmail.com',
    password: 'abc678',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'lMnFpQr',
    firstName: 'Anna',
    lastName: 'Lange',
    dateOfBirth: '1994-06-03',
    email: 'anna.lange2@gmail.com',
    password: 'password345',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'kJlMnOpQ',
    firstName: 'Maximilian',
    lastName: 'Graf',
    dateOfBirth: '1982-09-15',
    email: 'maximilian.graf@gmail.com',
    password: 'letmein123',
    jobWanted: 'Product Manager',
    researchStatus: 'Signed Up',
  },
  {
    id: 'iJkLmNoP',
    firstName: 'Sofia',
    lastName: 'Keller',
    dateOfBirth: '2003-12-28',
    email: 'sofia.keller@gmail.com',
    password: 'abc789',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'hIjKlMnO',
    firstName: 'Jakob',
    lastName: 'Hartmann',
    dateOfBirth: '1995-08-22',
    email: 'jakob.hartmann2@gmail.com',
    password: 'securepass456',
    jobWanted: 'UI Designer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'gHiJkLmN',
    firstName: 'Emma',
    lastName: 'Meyer',
    dateOfBirth: '1986-10-11',
    email: 'emma.meyer2@gmail.com',
    password: 'password234',
    jobWanted: 'Backend Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'fGhIjKlM',
    firstName: 'Ben',
    lastName: 'Braun',
    dateOfBirth: '2005-03-14',
    email: 'ben.braun@gmail.com',
    password: 'abc890',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Started Training',
  },
  {
    id: 'zYxWvUtS',
    firstName: 'Lina',
    lastName: 'Pohl',
    dateOfBirth: '1991-09-05',
    email: 'lina.pohl@gmail.com',
    password: 'letmein890',
    jobWanted: 'Software Engineer',
    researchStatus: 'Started Training',
  },
  {
    id: 'aBcDeFgI',
    firstName: 'Anna',
    lastName: 'Vogt',
    dateOfBirth: '1999-12-15',
    email: 'anna.vogt@gmail.com',
    password: 'securepass567',
    jobWanted: 'UX Designer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'jKlMnOpQ',
    firstName: 'Hanna',
    lastName: 'Wolf',
    dateOfBirth: '1987-07-28',
    email: 'hanna.wolf@gmail.com',
    password: 'abc012',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'bCdEfGhO',
    firstName: 'Emily',
    lastName: 'Schmitt',
    dateOfBirth: '1994-04-03',
    email: 'emily.schmitt@gmail.com',
    password: 'password789',
    jobWanted: 'Data Scientist',
    researchStatus: 'Searched Training',
  },
  {
    id: 'cDeFgHiP',
    firstName: 'Daniel',
    lastName: 'Wagner',
    dateOfBirth: '1982-11-19',
    email: 'daniel.wagner2@gmail.com',
    password: 'letmein345',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'dEfGhIjQ',
    firstName: 'Maria',
    lastName: 'Schultz',
    dateOfBirth: '2000-01-22',
    email: 'maria.schultz@gmail.com',
    password: 'securepass678',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Started Training',
  },
  {
    id: 'eFgHiJkR',
    firstName: 'Lea',
    lastName: 'Müller',
    dateOfBirth: '1996-06-14',
    email: 'lea.muller@gmail.com',
    password: 'password234',
    jobWanted: 'Data Analyst',
    researchStatus: 'Signed Up',
  },
  {
    id: 'fGhIjKlS',
    firstName: 'Niklas',
    lastName: 'Weber',
    dateOfBirth: '1989-03-07',
    email: 'niklas.weber@gmail.com',
    password: 'abc567',
    jobWanted: 'Software Developer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'gHiJkLmT',
    firstName: 'Liam',
    lastName: 'Winter',
    dateOfBirth: '1993-08-10',
    email: 'liam.winter@gmail.com',
    password: 'letmein901',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'hIjKlMnU',
    firstName: 'Sofia',
    lastName: 'Schulz',
    dateOfBirth: '2001-02-18',
    email: 'sofia.schulz@gmail.com',
    password: 'securepass345',
    jobWanted: 'UX Designer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'iJkLmNoV',
    firstName: 'Daniel',
    lastName: 'Braun',
    dateOfBirth: '1990-12-03',
    email: 'daniel.braun@gmail.com',
    password: 'password678',
    jobWanted: 'Software Engineer',
    researchStatus: 'Started Training',
  },
  {
    id: 'jKlMnOpW',
    firstName: 'Anna',
    lastName: 'Lange',
    dateOfBirth: '1984-10-26',
    email: 'anna.lange2@gmail.com',
    password: 'abc234',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'kLmNoPqX',
    firstName: 'Leon',
    lastName: 'Schäfer',
    dateOfBirth: '2003-05-09',
    email: 'leon.schafer@gmail.com',
    password: 'letmein567',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'lMnOpQrY',
    firstName: 'Amalia',
    lastName: 'Schwarz',
    dateOfBirth: '1985-09-17',
    email: 'amalia.schwarz@gmail.com',
    password: 'securepass890',
    jobWanted: 'Data Scientist',
    researchStatus: 'Searched Training',
  },
  {
    id: 'mNoPqRsZ',
    firstName: 'Jakob',
    lastName: 'Hartmann',
    dateOfBirth: '1997-04-11',
    email: 'jakob.hartmann3@gmail.com',
    password: 'password123',
    jobWanted: 'Backend Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'nOpQrStA',
    firstName: 'Sofia',
    lastName: 'Schulz',
    dateOfBirth: '2004-07-01',
    email: 'sofia.schulz2@gmail.com',
    password: 'abc456',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Started Training',
  },
  {
    id: 'oPqRsTuB',
    firstName: 'Oscar',
    lastName: 'Neumann',
    dateOfBirth: '1992-11-28',
    email: 'oscar.neumann2@gmail.com',
    password: 'letmein789',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'pQrStUvC',
    firstName: 'Sophia',
    lastName: 'Wolff',
    dateOfBirth: '1998-01-05',
    email: 'sophia.wolff2@gmail.com',
    password: 'securepass012',
    jobWanted: 'UI Designer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'qRsTuVwD',
    firstName: 'David',
    lastName: 'Hartmann',
    dateOfBirth: '1986-12-09',
    email: 'david.hartmann2@gmail.com',
    password: 'password345',
    jobWanted: 'Backend Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'rStUvWxE',
    firstName: 'Amalia',
    lastName: 'Kühn',
    dateOfBirth: '1995-03-20',
    email: 'amalia.kuhn@gmail.com',
    password: 'abc567',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'sTuVwXyF',
    firstName: 'Jakob',
    lastName: 'Lange',
    dateOfBirth: '2002-06-18',
    email: 'jakob.lange@gmail.com',
    password: 'letmein890',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'tUvWxYzG',
    firstName: 'Maria',
    lastName: 'Vogel',
    dateOfBirth: '1983-04-07',
    email: 'maria.vogel2@gmail.com',
    password: 'securepass567',
    jobWanted: 'Data Scientist',
    researchStatus: 'Signed Up',
  },
  {
    id: 'uVwXyZaH',
    firstName: 'Leon',
    lastName: 'Hermann',
    dateOfBirth: '2000-09-12',
    email: 'leon.hermann@gmail.com',
    password: 'password123',
    jobWanted: 'Software Engineer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'vWxYzAbI',
    firstName: 'Maria',
    lastName: 'Jäger',
    dateOfBirth: '1991-08-27',
    email: 'maria.jager@gmail.com',
    password: 'abc456',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'wXyZaBcJ',
    firstName: 'Finn',
    lastName: 'Braun',
    dateOfBirth: '1984-02-03',
    email: 'finn.braun2@gmail.com',
    password: 'letmein789',
    jobWanted: 'Backend Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'xYzAbCdK',
    firstName: 'Lena',
    lastName: 'Hofmann',
    dateOfBirth: '1997-05-22',
    email: 'lena.hofmann@gmail.com',
    password: 'securepass012',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Started Training',
  },
  {
    id: 'yZaBcDeL',
    firstName: 'Noah',
    lastName: 'Meyer',
    dateOfBirth: '1987-10-18',
    email: 'noah.meyer3@gmail.com',
    password: 'password234',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'zAbCdEfM',
    firstName: 'Emilia',
    lastName: 'Krüger',
    dateOfBirth: '1989-01-30',
    email: 'emilia.kruger@gmail.com',
    password: 'abc567',
    jobWanted: 'UI Designer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'bCdEfGhN',
    firstName: 'David',
    lastName: 'Hofmann',
    dateOfBirth: '1993-03-15',
    email: 'david.hofmann2@gmail.com',
    password: 'securepass789',
    jobWanted: 'Backend Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'cDeFgHiO',
    firstName: 'Emma',
    lastName: 'Böhm',
    dateOfBirth: '1995-07-09',
    email: 'emma.bohm@gmail.com',
    password: 'letmein890',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'dEfGhIjP',
    firstName: 'Paul',
    lastName: 'Wagner',
    dateOfBirth: '2002-11-21',
    email: 'paul.wagner3@gmail.com',
    password: 'abc012',
    jobWanted: 'Software Engineer',
    researchStatus: 'Started Training',
  },
  {
    id: 'eFgHiJkQ',
    firstName: 'Finn',
    lastName: 'Schneider',
    dateOfBirth: '1988-12-16',
    email: 'finn.schneider2@gmail.com',
    password: 'password123',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'fGhIjKlR',
    firstName: 'Sophie',
    lastName: 'Becker',
    dateOfBirth: '1997-04-07',
    email: 'sophie.becker@gmail.com',
    password: 'abc456',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'gHiJkLmS',
    firstName: 'Lukas',
    lastName: 'Müller',
    dateOfBirth: '1999-06-20',
    email: 'lukas.muller2@gmail.com',
    password: 'letmein789',
    jobWanted: 'Backend Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'hIjKlMnT',
    firstName: 'Lina',
    lastName: 'Lange',
    dateOfBirth: '2003-09-24',
    email: 'lina.lange3@gmail.com',
    password: 'securepass012',
    jobWanted: 'Data Scientist',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'iJkLmNoU',
    firstName: 'Finn',
    lastName: 'Hoffmann2',
    dateOfBirth: '2001-12-25',
    email: 'finn.hoffmann2@gmail.com',
    password: 'abc345',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Started Training',
  },
  // Continue here
  {
    id: 'jKlMnOpV',
    firstName: 'Timo',
    lastName: 'Keller',
    dateOfBirth: '1987-09-28',
    email: 'timo.keller@gmail.com',
    password: 'password789',
    jobWanted: 'Data Scientist',
    researchStatus: 'Signed Up',
  },
  {
    id: 'kLmNoPqW',
    firstName: 'Laura',
    lastName: 'Graf',
    dateOfBirth: '2001-11-22',
    email: 'laura.graf@gmail.com',
    password: 'securepass567',
    jobWanted: 'Software Engineer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'lMnOpQrX',
    firstName: 'David',
    lastName: 'Vogel',
    dateOfBirth: '1996-10-17',
    email: 'david.vogel@gmail.com',
    password: 'abc234',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'mNoPqRsY',
    firstName: 'Emilia',
    lastName: 'Braun',
    dateOfBirth: '1992-01-08',
    email: 'emilia.braun@gmail.com',
    password: 'letmein890',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'nOpQrStZ',
    firstName: 'Paul',
    lastName: 'Pohl',
    dateOfBirth: '1989-04-19',
    email: 'paul.pohl@gmail.com',
    password: 'securepass345',
    jobWanted: 'Backend Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'oPqRsTuA',
    firstName: 'Amalia',
    lastName: 'Schulze',
    dateOfBirth: '1998-07-11',
    email: 'amalia.schulze@gmail.com',
    password: 'password567',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'pQrStUvB',
    firstName: 'Felix',
    lastName: 'Jung',
    dateOfBirth: '2002-12-30',
    email: 'felix.jung@gmail.com',
    password: 'abc123',
    jobWanted: 'UI Designer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'qRsTuVwC',
    firstName: 'Hanna',
    lastName: 'Winter',
    dateOfBirth: '1985-02-25',
    email: 'hanna.winter@gmail.com',
    password: 'letmein456',
    jobWanted: 'Data Scientist',
    researchStatus: 'Searched Training',
  },
  {
    id: 'rStUvWxD',
    firstName: 'Alexander',
    lastName: 'Meier',
    dateOfBirth: '2000-06-18',
    email: 'alexander.meier@gmail.com',
    password: 'securepass789',
    jobWanted: 'Backend Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'sTuVwXyE',
    firstName: 'Maria',
    lastName: 'Vogt',
    dateOfBirth: '1984-09-30',
    email: 'maria.vogt@gmail.com',
    password: 'password234',
    jobWanted: 'Software Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'tUvWxYzF',
    firstName: 'Niklas',
    lastName: 'Müller',
    dateOfBirth: '1992-01-12',
    email: 'niklas.muller@gmail.com',
    password: 'abc567',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'uVwXyZaG',
    firstName: 'Sarah',
    lastName: 'Schneider',
    dateOfBirth: '1987-04-15',
    email: 'sarah.schneider@gmail.com',
    password: 'letmein890',
    jobWanted: 'UX Designer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'vWxYzAbH',
    firstName: 'Lukas',
    lastName: 'Hoffmann',
    dateOfBirth: '1995-06-28',
    email: 'lukas.hoffmann@gmail.com',
    password: 'securepass012',
    jobWanted: 'Software Engineer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'wXyZaBcI',
    firstName: 'Mia',
    lastName: 'Schulz',
    dateOfBirth: '2001-03-18',
    email: 'mia.schulz@gmail.com',
    password: 'password567',
    jobWanted: 'Data Analyst',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'xYzAbCdJ',
    firstName: 'Emma',
    lastName: 'Lange',
    dateOfBirth: '1994-08-12',
    email: 'emma.lange@gmail.com',
    password: 'abc234',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'yZaBcDeK',
    firstName: 'Noah',
    lastName: 'Wolf',
    dateOfBirth: '1988-02-23',
    email: 'noah.wolf@gmail.com',
    password: 'letmein567',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'zAbCdEfL',
    firstName: 'Timo',
    lastName: 'Schwarz',
    dateOfBirth: '2004-04-15',
    email: 'timo.schwarz@gmail.com',
    password: 'securepass789',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'bCdEfGhM',
    firstName: 'Lena',
    lastName: 'Keller',
    dateOfBirth: '1990-07-19',
    email: 'lena.keller@gmail.com',
    password: 'password012',
    jobWanted: 'UX Designer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'cDeFgHiN',
    firstName: 'Maximilian',
    lastName: 'Graf',
    dateOfBirth: '1986-09-23',
    email: 'maximilian.graf@gmail.com',
    password: 'abc567',
    jobWanted: 'Software Engineer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'dEfGhIjO',
    firstName: 'Hannah',
    lastName: 'Vogel',
    dateOfBirth: '1993-11-14',
    email: 'hannah.vogel@gmail.com',
    password: 'letmein890',
    jobWanted: 'Data Scientist',
    researchStatus: 'Started Training',
  },
  {
    id: 'eFgHiJkP',
    firstName: 'Ben',
    lastName: 'Braun',
    dateOfBirth: '1999-12-16',
    email: 'ben.braun@gmail.com',
    password: 'securepass234',
    jobWanted: 'Backend Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'fGhIjKlQ',
    firstName: 'Sophia',
    lastName: 'Pohl',
    dateOfBirth: '2003-08-29',
    email: 'sophia.pohl@gmail.com',
    password: 'password567',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'gHiJkLmR',
    firstName: 'Elias',
    lastName: 'Schulze',
    dateOfBirth: '1984-07-18',
    email: 'elias.schulze@gmail.com',
    password: 'abc890',
    jobWanted: 'Software Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'hIjKlMnS',
    firstName: 'Laura',
    lastName: 'Jung',
    dateOfBirth: '1991-02-22',
    email: 'laura.jung@gmail.com',
    password: 'letmein123',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'iJkLmNoT',
    firstName: 'Paul',
    lastName: 'Winter',
    dateOfBirth: '1996-05-26',
    email: 'paul.winter@gmail.com',
    password: 'abc456',
    jobWanted: 'UX Designer',
    researchStatus: 'Started Training',
  },
  {
    id: 'jKlMnOpU',
    firstName: 'Emilia',
    lastName: 'Meier',
    dateOfBirth: '2000-09-30',
    email: 'emilia.meier@gmail.com',
    password: 'password789',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'kLmNoPqV',
    firstName: 'Niklas',
    lastName: 'Vogt',
    dateOfBirth: '1989-01-23',
    email: 'niklas.vogt@gmail.com',
    password: 'letmein012',
    jobWanted: 'Data Analyst',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'lMnOpQrW',
    firstName: 'Sarah',
    lastName: 'Schneider',
    dateOfBirth: '1995-04-17',
    email: 'sarah.schneider@gmail.com',
    password: 'abc567',
    jobWanted: 'Software Engineer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'mNoPqRsX',
    firstName: 'Alexander',
    lastName: 'Schmitt',
    dateOfBirth: '1987-06-12',
    email: 'alexander.schmitt@gmail.com',
    password: 'securepass890',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'nOpQrStY',
    firstName: 'Mia',
    lastName: 'Weber',
    dateOfBirth: '2001-07-15',
    email: 'mia.weber@gmail.com',
    password: 'password123',
    jobWanted: 'UX Designer',
    researchStatus: 'Started Training',
  },
  {
    id: 'oPqRsTuZ',
    firstName: 'Felix',
    lastName: 'Fischer',
    dateOfBirth: '1983-10-29',
    email: 'felix.fischer@gmail.com',
    password: 'letmein456',
    jobWanted: 'Data Scientist',
    researchStatus: 'Signed Up',
  },
  {
    id: 'pQrStUvA',
    firstName: 'Maria',
    lastName: 'Wagner',
    dateOfBirth: '1998-12-05',
    email: 'maria.wagner@gmail.com',
    password: 'securepass789',
    jobWanted: 'Software Engineer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'qRsTuVwB',
    firstName: 'Niklas',
    lastName: 'Graf',
    dateOfBirth: '1986-03-18',
    email: 'niklas.graf@gmail.com',
    password: 'abc012',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'rStUvWxC',
    firstName: 'Sarah',
    lastName: 'Schwarz',
    dateOfBirth: '1992-06-30',
    email: 'sarah.schwarz@gmail.com',
    password: 'letmein345',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'sTuVwXyD',
    firstName: 'Niklas',
    lastName: 'Meyer',
    dateOfBirth: '1996-08-14',
    email: 'niklas.meyer@gmail.com',
    password: 'abc567',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'tUvWxYzE',
    firstName: 'Maria',
    lastName: 'Weber',
    dateOfBirth: '2000-11-27',
    email: 'maria.weber@gmail.com',
    password: 'password789',
    jobWanted: 'Backend Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'uVwXyZaF',
    firstName: 'Niklas',
    lastName: 'Graf',
    dateOfBirth: '1984-02-10',
    email: 'niklas.graf@gmail.com',
    password: 'letmein012',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'vWxYzAbG',
    firstName: 'Maria',
    lastName: 'Schwarz',
    dateOfBirth: '1998-05-22',
    email: 'maria.schwarz@gmail.com',
    password: 'abc345',
    jobWanted: 'Software Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'wXyZaBcH',
    firstName: 'Niklas',
    lastName: 'Jäger',
    dateOfBirth: '1985-09-15',
    email: 'niklas.jager@gmail.com',
    password: 'letmein567',
    jobWanted: 'UI Designer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'xYzAbCdI',
    firstName: 'Maria',
    lastName: 'Fischer',
    dateOfBirth: '1999-12-18',
    email: 'maria.fischer@gmail.com',
    password: 'abc789',
    jobWanted: 'Mobile App Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'yZaBcDeJ',
    firstName: 'Niklas',
    lastName: 'Graf',
    dateOfBirth: '2003-01-20',
    email: 'niklas.graf@gmail.com',
    password: 'letmein012',
    jobWanted: 'Data Analyst',
    researchStatus: 'Signed Up',
  },
  {
    id: 'zAbCdEfK',
    firstName: 'Maria',
    lastName: 'Schwarz',
    dateOfBirth: '1987-03-24',
    email: 'maria.schwarz@gmail.com',
    password: 'abc234',
    jobWanted: 'UI/UX Designer',
    researchStatus: 'Entered Criteria',
  },
  {
    id: 'bCdEfGhL',
    firstName: 'Niklas',
    lastName: 'Jäger',
    dateOfBirth: '1992-05-28',
    email: 'niklas.jager@gmail.com',
    password: 'letmein456',
    jobWanted: 'Front-End Developer',
    researchStatus: 'Searched Training',
  },
  {
    id: 'cDeFgHiM',
    firstName: 'Maria',
    lastName: 'Fischer',
    dateOfBirth: '1996-09-30',
    email: 'maria.fischer@gmail.com',
    password: 'abc567',
    jobWanted: 'Software Engineer',
    researchStatus: 'Selected a Training Partner',
  },
  {
    id: 'dEfGhIjN',
    firstName: 'Niklas',
    lastName: 'Graf',
    dateOfBirth: '1988-12-03',
    email: 'niklas.graf@gmail.com',
    password: 'letmein789',
    jobWanted: 'Full-Stack Developer',
    researchStatus: 'Started Training',
  },
  {
    id: 'eFgHiJkO',
    firstName: 'Maria',
    lastName: 'Schwarz',
    dateOfBirth: '1993-03-07',
    email: 'maria.schwarz@gmail.com',
    password: 'abc890',
    jobWanted: 'Backend Developer',
    researchStatus: 'Signed Up',
  },
  {
    id: 'fGhIjKlP',
    firstName: 'Niklas',
    lastName: 'Jäger',
    dateOfBirth: '1998-07-10',
    email: 'niklas.jager@gmail.com',
    password: 'letmein012',
    jobWanted: 'DevOps Engineer',
    researchStatus: 'Entered Criteria',
  },
];

const ids = new Set<string | number>();
const duplicateIDs = new Set<string | number>();
for (const user of users) {
  user.email = md5(user.email);
  user.password = md5(user.password);
  if (ids.has(user.id)) {
    duplicateIDs.add(user.id);
  } else {
    ids.add(user.id);
  }
}

if (duplicateIDs.size) {
  console.warn('Duplicate IDs:', Array.from(duplicateIDs));
} else {
  // console.warn('No duplicate ID');
}
